name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build JAR (Java 8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'
      - name: Package (skip tests for now)
        run: mvn -B -DskipTests package
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  publish-image:
    name: Build & Push Docker Image to GHCR
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_REF: ghcr.io/shubhamdarge/employee-portal-backend
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t $IMAGE_REF:${{ github.sha }} -t $IMAGE_REF:latest .
      - name: Push image
        run: |
          docker push $IMAGE_REF:${{ github.sha }}
          docker push $IMAGE_REF:latest
